const cv=document.querySelector('#world'),cx=cv.getContext('2d'),$=s=>document.querySelector(s),T=40,COLS=36,ROWS=20,WW=COLS*T,WH=ROWS*T,KEY='catyard-v3',OLD='catyard-v2';
const breeds=[{defaultName:'奶糖',breed:'橘猫',coat:'#d99052',icon:'🐈',bio:'亲人又贪吃，最爱在太阳底下打盹。'},{defaultName:'煤球',breed:'黑猫',coat:'#4a4653',icon:'🐈‍⬛',bio:'安静慢热，熟悉之后会一直跟着你。'},{defaultName:'芝麻',breed:'狸花猫',coat:'#9d8e7e',icon:'🐈',bio:'聪明机灵，喜欢探索院子的每个角落。'},{defaultName:'豆包',breed:'奶牛猫',coat:'#e5dccd',icon:'🐈',bio:'活泼爱玩，看到新玩具就走不动。'},{defaultName:'蓝莓',breed:'布偶猫',coat:'#d8c7b8',icon:'🐈',bio:'温柔黏人，有一双亮晶晶的蓝眼睛。'},{defaultName:'年糕',breed:'英国短毛猫',coat:'#89919b',icon:'🐈',bio:'圆滚滚很淡定，喜欢舒适安静的小窝。'},{defaultName:'海苔',breed:'暹罗猫',coat:'#e8d5b8',icon:'🐈',bio:'好奇爱聊天，哪里热闹就往哪里跑。'},{defaultName:'栗子',breed:'缅因猫',coat:'#886c58',icon:'🐈',bio:'大个子温柔猫，最喜欢爬高和看风景。'}];
const mapsDef=[{id:'yard',name:'阳光小院',theme:0},{id:'forest',name:'林间空地',theme:1},{id:'coast',name:'海风沙滩',theme:2}];const defs=[
{id:'food',icon:'🥣',name:'猫粮碗',cat:'food',cost:10,desc:'自动喂食，饱腹 +22',auto:true,hunger:22,mood:3},
{id:'toy',icon:'🧶',name:'毛线球',cat:'play',cost:13,desc:'追着玩，开心 +10',auto:true,mood:10},
{id:'water',icon:'💧',name:'清水碗',cat:'food',cost:8,desc:'喝水休息，开心 +4',auto:true,mood:4},
{id:'bed',icon:'🧺',name:'软软睡垫',cat:'rest',cost:16,desc:'打盹休息，开心 +6',auto:true,mood:6},
{id:'scratch',icon:'🪵',name:'抓抓柱',cat:'play',cost:15,desc:'磨爪玩耍，开心 +7',auto:true,mood:7},
{id:'fishcan',icon:'🐟',name:'鱼罐头',cat:'food',cost:22,desc:'一次性美味，饱腹 +50',auto:true,consumable:true,hunger:50,mood:12},
{id:'treat',icon:'🍪',name:'猫咪零食',cat:'food',cost:14,desc:'一次性奖励，开心 +16',auto:true,consumable:true,hunger:10,mood:16},
{id:'wand',icon:'🪶',name:'羽毛逗猫棒',cat:'play',cost:18,desc:'点击使用，开心 +18',manual:true,mood:18},
{id:'bell',icon:'🔔',name:'铃铛球',cat:'play',cost:15,desc:'追逐铃铛，开心 +12',auto:true,mood:12},
{id:'box',icon:'📦',name:'纸箱',cat:'rest',cost:12,desc:'钻进纸箱，开心 +8',auto:true,mood:8},
{id:'tunnel',icon:'🌀',name:'猫隧道',cat:'play',cost:20,desc:'穿梭探险，开心 +13',auto:true,mood:13},
{id:'tree',icon:'🌳',name:'猫爬架',cat:'rest',cost:28,desc:'攀爬瞭望，开心 +15',auto:true,mood:15},
{id:'catnip',icon:'🌿',name:'猫薄荷盆栽',cat:'rest',cost:17,desc:'吸引猫咪，开心 +12',auto:true,mood:12,attract:2},
{id:'brush',icon:'🪮',name:'梳毛刷',cat:'play',cost:16,desc:'点击梳毛，开心 +14',manual:true,mood:14},
{id:'window',icon:'🪟',name:'窗台软垫',cat:'rest',cost:21,desc:'晒太阳休息，开心 +11',auto:true,mood:11}
];const filters=[['all','全部'],['food','食物'],['play','玩耍'],['rest','休息 / 环境']];
function dayKey(){return new Date().toLocaleDateString('sv-SE')}function makeCat(kind,x,y,i=0){let b=breeds[kind];return{id:`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}-${i}`,kind,name:b.defaultName,x,y,mood:62,hunger:48,target:null,actionWait:0,face:1}}
function emptyMap(id,kind){return{id,objects:[],cats:[makeCat(kind,WW*.5,WH*.45)],camera:{x:0,y:0,zoom:1.12,initialized:false}}}function baseState(){return{coins:24,day:1,visits:1,placed:0,claimed:false,mapId:'yard',maps:{yard:emptyMap('yard',0),forest:emptyMap('forest',4),coast:emptyMap('coast',6)},daily:{date:dayKey(),feed:0,play:0,visitors:0,claimed:{}}}}
const dailyDefs=[{id:'feed',name:'猫咪食堂',desc:'喂食猫咪 6 次',goal:6,reward:10},{id:'play',name:'快乐时光',desc:'陪猫咪玩耍 6 次',goal:6,reward:12},{id:'visit',name:'新朋友来访',desc:'迎接 3 只新猫咪',goal:3,reward:16}];function fixCat(c,i){let k=Math.max(0,Math.min(breeds.length-1,Number(c.kind)||0));return{...c,id:c.id||`legacy-${k}-${i}`,kind:k,name:String(c.name||c.nickname||breeds[k].defaultName).slice(0,12),mood:Number.isFinite(c.mood)?c.mood:60,hunger:Number.isFinite(c.hunger)?c.hunger:50,x:Number.isFinite(c.x)?c.x:WW*.5,y:Number.isFinite(c.y)?c.y:WH*.45,target:null,actionWait:0}}
function loadState(){let saved=null;try{saved=JSON.parse(localStorage.getItem(KEY)||'null')}catch{}let legacy=false;if(!saved){try{saved=JSON.parse(localStorage.getItem(OLD)||'null');legacy=!!saved}catch{}}let s;if(!saved)s=baseState();else if(legacy){s=baseState();let oldCoins=Number(saved.coins);s.coins=Math.min(36,Math.max(0,Number.isFinite(oldCoins)?Math.floor(oldCoins):24));s.day=saved.day||1;s.visits=saved.visits||1;s.placed=saved.placed||0;s.claimed=!!saved.claimed;s.maps.yard.objects=Array.isArray(saved.objects)?saved.objects:[];s.maps.yard.cats=Array.isArray(saved.cats)?saved.cats.map(fixCat):s.maps.yard.cats;s.maps.yard.camera={x:0,y:0,zoom:1.12,initialized:false}}else s=saved;
if(!s.maps||typeof s.maps!=='object')s.maps=baseState().maps;for(let [i,m] of mapsDef.entries()){if(!s.maps[m.id])s.maps[m.id]=emptyMap(m.id,[0,4,6][i]);let mp=s.maps[m.id];mp.objects=Array.isArray(mp.objects)?mp.objects:[];mp.cats=Array.isArray(mp.cats)?mp.cats.map(fixCat):[];mp.cats.forEach((c,i)=>Object.assign(c,fixCat(c,i)));mp.camera=mp.camera||{x:0,y:0,zoom:1.12,initialized:false};if(mp.camera.initialized===undefined)mp.camera.initialized=false;mp.camera.zoom=Math.max(.7,Math.min(3,mp.camera.zoom||1.12))}
s.mapId=mapsDef.some(m=>m.id===s.mapId)?s.mapId:'yard';s.coins=Math.max(0,Math.floor(Number(s.coins)||0));s.visits=Math.max(1,s.visits||1);s.placed=Math.max(0,s.placed||0);if(!s.daily||s.daily.date!==dayKey()){s.day=Math.max(1,s.day||1)+(s.daily?1:0);s.daily={date:dayKey(),feed:0,play:0,visitors:0,claimed:{}}}s.daily.claimed=s.daily.claimed||{};if(legacy)try{localStorage.setItem(KEY,JSON.stringify(s))}catch{}return s}
let state=loadState(),activeFilter='all',selected=null,eraseMode=false,hover=null,toastTimer=null,soundOn=true,renaming=null,applyingRemote=false;const getMap=()=>state.maps[state.mapId],getCats=()=>getMap().cats,getObjects=()=>getMap().objects;
function save(forceCats=false){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}if(!applyingRemote&&window.catOnline?.stateChanged)window.catOnline.stateChanged(sharedSnapshot(),forceCats)}function sharedSnapshot(){return{mapId:state.mapId,maps:Object.fromEntries(mapsDef.map(m=>[m.id,{objects:state.maps[m.id].objects,cats:state.maps[m.id].cats,camera:state.maps[m.id].camera}]))}}
const sessionNotices=new Set();try{JSON.parse(sessionStorage.getItem('catyard-notices')||'[]').forEach(k=>sessionNotices.add(k))}catch{}function msg(key,text){if(sessionNotices.has(key))return;sessionNotices.add(key);try{sessionStorage.setItem('catyard-notices',JSON.stringify([...sessionNotices]))}catch{}const n=$('#toast');n.textContent=text;n.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove('show'),1800)}function beep(f=600){if(!soundOn)return;try{let a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.value=.022;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.055);o.onended=()=>a.close()}catch{}}function setVisitText(t){$('#visitMessage').textContent=t}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderVisitors(){let root=$('#visitors'),cats=getCats();if(!cats.length){root.innerHTML='<div class="visitors-empty">还没有猫咪来访，摆些食物和玩具试试。</div>';return}root.innerHTML=cats.map(c=>{let b=breeds[c.kind],editing=renaming===c.id;return`<article class="visitor-row" data-cat="${esc(c.id)}"><span class="visitor-avatar">${b.icon}</span><div class="visitor-info">${editing?`<input class="rename-input" data-rename-input="${esc(c.id)}" value="${esc(c.name)}" maxlength="12" aria-label="编辑猫咪昵称">`:`<div class="visitor-topline"><button class="visitor-name" data-cat-name="${esc(c.id)}" title="双击编辑昵称">${esc(c.name)}</button><span class="breed-tag">${b.breed}</span></div>`}<small class="visitor-desc">${b.bio}</small><span class="visitor-state">🍚 饱腹 ${Math.round(100-c.hunger)}% · 💗 开心 ${Math.round(c.mood)}%</span></div><button class="rename-btn" data-edit-cat="${esc(c.id)}" aria-label="编辑${esc(c.name)}昵称">✎</button></article>`}).join('');if(renaming){let input=root.querySelector(`[data-rename-input="${CSS.escape(renaming)}"]`);if(input){input.focus();input.select();input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();commitRename(renaming,input.value)}if(e.key==='Escape'){e.preventDefault();renaming=null;renderVisitors()}};input.onblur=()=>{if(renaming===input.dataset.renameInput)commitRename(renaming,input.value)}}}}
function beginRename(id){renaming=id;renderVisitors()}function commitRename(id,value){let c=getCats().find(x=>x.id===id);if(!c){renaming=null;renderVisitors();return}let name=Array.from(String(value).trim()).slice(0,12).join('');if(name)c.name=name;renaming=null;renderVisitors();save();if(name)msg('rename','昵称已保存。')}
function renderFilters(){$('#itemFilters').innerHTML=filters.map(([id,label])=>`<button class="tool-filter ${activeFilter===id?'active':''}" data-filter="${id}">${label}${id==='all'?' · '+defs.length:''}</button>`).join('')}
function renderTools(){let list=defs.filter(d=>activeFilter==='all'||d.cat===activeFilter);$('#tools').innerHTML=list.map(d=>`<button class="tool ${selected===d.id?'active':''}" data-tool="${d.id}"><span class="tool-icon">${d.icon}</span><span><b>${d.name}</b><small>🪙 ${d.cost} · ${d.desc}${d.consumable?' · 用后消耗':''}</small></span></button>`).join('')}
function renderQuests(){let d=state.daily;$('#dailyQuests').innerHTML=dailyDefs.map(q=>{let value=d[q.id]||0,claimed=!!d.claimed[q.id],pct=Math.min(100,value/q.goal*100);return`<div class="quest-row"><span class="quest-title">${q.name}</span><span class="quest-reward">🪙 ${q.reward}</span><span class="quest-desc">${q.desc}（${Math.min(value,q.goal)}/${q.goal}）</span><div class="quest-progress"><i style="width:${pct}%"></i></div><button class="quest-claim" data-quest="${q.id}" ${claimed||value<q.goal?'disabled':''}>${claimed?'已领取':value>=q.goal?'领取奖励':'继续完成'}</button></div>`}).join('')}
function ui({roster=false,quests=false}={}){let cats=getCats(),cat=cats[0]||makeCat(0,WW/2,WH/2);$('#coins').textContent=state.coins;$('#day').textContent=state.day;$('#visitorCount').textContent=cats.length+' 只';$('#loveNum').textContent=Math.round(cat.mood)+'%';$('#loveBar').style.width=cat.mood+'%';$('#hunger').textContent=Math.round(100-cat.hunger)+'%';$('#happy').textContent=Math.round(cat.mood)+'%';$('#missionBar').style.width=Math.min(100,state.placed/2*100)+'%';$('#missionText').textContent=state.claimed?'原有任务已完成，猫咪们很喜欢这里！':`摆放 2 件物品（${Math.min(2,state.placed)}/2），让猫咪开心起来`;$('#claim').disabled=state.claimed||state.placed<2;$('#claim').textContent=state.claimed?'奖励已领取':'完成目标领金币';$('#mapSelect').value=state.mapId;$('#mapName').textContent=mapsDef.find(m=>m.id===state.mapId).name;if(roster)renderVisitors();if(quests)renderQuests()}
let viewport={w:800,h:480,dpr:1},hoverTile=null,pointers=new Map(),gesture=null,pinch=null;function resizeCanvas(){let r=cv.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,2);viewport={w:Math.max(1,r.width),h:Math.max(1,r.height),dpr:d};let w=Math.round(viewport.w*d),h=Math.round(viewport.h*d);if(cv.width!==w||cv.height!==h){cv.width=w;cv.height=h}if(!camera().initialized)centerCamera();clampCamera()}window.addEventListener('resize',resizeCanvas);new ResizeObserver(resizeCanvas).observe(cv);function camera(){let m=getMap();return m.camera||(m.camera={x:0,y:0,zoom:1.15,initialized:false})}function projection(){let fit=Math.min(viewport.w/WW,viewport.h/WH),scale=fit*camera().zoom,drawW=WW*scale,drawH=WH*scale,ox=drawW<viewport.w?(viewport.w-drawW)/2:0,oy=drawH<viewport.h?(viewport.h-drawH)/2:0;return{scale,ox,oy,tx:ox-camera().x*scale,ty:oy-camera().y*scale}}
function centerCamera(){let c=camera(),scale=Math.min(viewport.w/WW,viewport.h/WH)*c.zoom;c.x=Math.max(0,(WW-viewport.w/scale)/2);c.y=Math.max(0,(WH-viewport.h/scale)/2);c.initialized=true;clampCamera()}function clampCamera(){let c=camera(),p=projection(),maxX=Math.max(0,WW-viewport.w/p.scale),maxY=Math.max(0,WH-viewport.h/p.scale);c.x=Math.max(0,Math.min(maxX,c.x));c.y=Math.max(0,Math.min(maxY,c.y))}function pointWorld(clientX,clientY){let r=cv.getBoundingClientRect(),p=projection(),sx=clientX-r.left,sy=clientY-r.top;return{x:(sx-p.ox)/p.scale+camera().x,y:(sy-p.oy)/p.scale+camera().y,sx,sy}}
function R(x,y,w,h,color){cx.fillStyle=color;cx.fillRect(x,y,w,h)}function tileColor(map,x,y){let v=(x*13+y*7)%6;if(map==='yard'){if(y<7)return v%2?'#d99d6a':'#e4ae78';return v%3===0?'#89b876':v%2?'#8fbe7b':'#84b271'}if(map==='forest'){if(x>27&&y<7)return '#75b9c0';return v%3===0?'#61915d':v%2?'#72a566':'#67975f'}if(y<5||y>16)return v%2?'#71b8c8':'#79c1ce';return v%3===0?'#ead39c':v%2?'#e4c98e':'#efd8a4'}
function drawMap(){let id=state.mapId,c=camera(),pw=viewport.w/projection().scale,ph=viewport.h/projection().scale,x0=Math.max(0,Math.floor(c.x/T)-1),x1=Math.min(COLS,Math.ceil((c.x+pw)/T)+1),y0=Math.max(0,Math.floor(c.y/T)-1),y1=Math.min(ROWS,Math.ceil((c.y+ph)/T)+1);for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){let col=tileColor(id,x,y);if(id==='forest'&&Math.abs(x-(y*.78+5))<1.1)col='#c5a977';if(id==='coast'&&x>7&&x<29&&y>8&&y<11)col='#ba966d';R(x*T,y*T,T,T,col);cx.globalAlpha=.12;R(x*T+2,y*T+2,T-4,T-4,id==='coast'?'#fff5cb':'#e8efb3');cx.globalAlpha=1;cx.strokeStyle='rgba(55,52,74,.08)';cx.strokeRect(x*T+.5,y*T+.5,T,T)}
if(id==='yard'){R(0,0,WW,34,'#ae7057');for(let x=0;x<WW;x+=55)R(x,0,3,34,'#955e4e');R(120,48,115,42,'#f4d99d');R(126,54,103,29,'#a4d5d8');R(570,58,96,35,'#c88967');R(620,48,9,12,'#f1d18c')}else if(id==='forest'){for(let x=2;x<COLS;x+=5){R(x*T,2*T,34,26,'#4e8053');R((x+.3)*T,2*T-12,22,17,'#78aa62');R((x+.6)*T,ROWS*T-58,26,34,'#548650')}for(let i=0;i<12;i++){let x=(i*11+4)%COLS,y=(i*7+3)%ROWS;R(x*T+12,y*T+12,5,5,i%2?'#f4d76e':'#f19ba6')}}else{for(let x=1;x<COLS;x+=6){R(x*T,5*T,8,6*T,'#ae895f');R((x+2)*T,6*T,25,4,'#f7e2ae')}for(let i=0;i<20;i++){let x=(i*13+2)%COLS,y=12+(i*3)%6;R(x*T+10,y*T+12,5,3,i%2?'#fff1d0':'#efc9a8')}}}
function drawBowl(x,y,color='#df8b6c'){R(x+5,y+25,30,4,'#574655');R(x+6,y+15,28,10,color);R(x+9,y+12,22,4,'#f5d69c');R(x+13,y+17,14,3,'#f3cf72')}function drawObject(o){let x=o.x*T,y=o.y*T;switch(o.type){case'food':drawBowl(x,y);break;case'water':drawBowl(x,y,'#79c9d0');break;case'toy':case'bell':R(x+11,y+15,19,19,o.type==='toy'?'#db7895':'#e6be56');R(x+13,y+12,16,16,o.type==='toy'?'#ed9fb0':'#f2d979');R(x+18,y+11,4,18,o.type==='toy'?'#f6dc73':'#af779d');R(x+12,y+19,18,4,o.type==='toy'?'#9c80bd':'#f6e6a8');break;case'bed':case'window':R(x+3,y+12,34,24,'#8f6a86');R(x+7,y+8,26,23,o.type==='bed'?'#e99baa':'#95c9d2');R(x+12,y+13,17,12,'#ffe7d6');break;case'scratch':R(x+17,y+10,9,26,'#c4875d');R(x+12,y+8,20,5,'#7b5368');R(x+12,y+33,20,5,'#9a6952');for(let a=14;a<31;a+=7)R(x+18,y+a,7,3,'#ead19b');break;case'fishcan':R(x+10,y+11,21,23,'#d56658');R(x+12,y+8,17,5,'#e5c98a');R(x+15,y+17,12,8,'#f4d27a');R(x+18,y+19,7,4,'#d88958');break;case'treat':R(x+10,y+15,21,16,'#e5b366');R(x+13,y+12,15,4,'#f6db9e');R(x+18,y+20,6,6,'#c97562');break;case'wand':R(x+7,y+26,27,4,'#8c634f');R(x+29,y+11,4,18,'#84618d');R(x+22,y+8,9,8,'#d87b9b');R(x+32,y+8,6,10,'#f3cf70');break;case'box':R(x+7,y+15,27,20,'#bb855e');R(x+11,y+10,19,7,'#dbad79');R(x+17,y+22,8,13,'#715b67');break;case'tunnel':R(x+5,y+13,30,22,'#8c7eaa');R(x+11,y+10,18,23,'#dca1a4');R(x+15,y+14,10,20,'#51475b');break;case'tree':R(x+14,y+12,12,25,'#a67b57');R(x+7,y+30,27,6,'#7e5b51');R(x+8,y+9,26,6,'#8b70a4');R(x+13,y+2,17,6,'#e9a3ad');break;case'catnip':R(x+8,y+23,25,12,'#c58364');R(x+6,y+20,29,5,'#98635a');R(x+12,y+8,5,13,'#619861');R(x+19,y+4,5,17,'#70a96c');R(x+25,y+10,5,11,'#79b576');break;case'brush':R(x+9,y+22,24,9,'#a87659');R(x+13,y+15,16,8,'#e2b887');for(let a=14;a<30;a+=5)R(x+a,y+11,2,7,'#76617e');break}}
function drawCat(c){let x=Math.round(c.x),y=Math.round(c.y+Math.sin(performance.now()/220+c.x)*1.3),coat=breeds[c.kind].coat;R(x-10,y+4,21,13,coat);R(x-14,y+7,4,8,coat);R(x+10,y+7,4,8,coat);R(x-9,y+15,5,4,'#f6e5cd');R(x+5,y+15,5,4,'#f6e5cd');R(x-11,y-8,22,15,coat);R(x-10,y-13,7,8,coat);R(x+4,y-13,7,8,coat);R(x-8,y-11,3,4,'#eda0a0');R(x+5,y-11,3,4,'#eda0a0');R(x-7,y-3,3,4,'#352f40');R(x+4,y-3,3,4,'#352f40');R(x-2,y+2,4,3,'#e98591');R(x-5,y+4,3,2,'#fff2de');R(x+3,y+4,3,2,'#fff2de');R(x-18,y+3,7,2,coat);R(x-22,y,6,3,coat);R(x-20,y-5,6,3,coat);if(c.kind===0||c.kind===2||c.kind===7){R(x-3,y-12,3,6,'#f8d190');R(x+2,y-10,3,5,'#f8d190')}if(c.kind===3){R(x-10,y-7,8,7,'#4a4653');R(x+4,y+7,7,8,'#4a4653')}if(c.kind===4||c.kind===6){R(x-10,y-11,5,8,'#70675f');R(x+5,y-11,5,8,'#70675f');R(x-4,y-3,10,8,'#9b8172')}if(c.kind===6){R(x-9,y+12,5,7,'#6a5d59');R(x+5,y+12,5,7,'#6a5d59')}if(c.kind===7){R(x-10,y+6,5,3,'#5e4a3e');R(x+5,y+8,5,3,'#5e4a3e')}if(c.bubbleUntil>Date.now()){R(x+12,y-31,14,12,'#fff5df');R(x+16,y-27,5,4,'#ea8094')}}
function paint(){resizeCanvas();cx.setTransform(viewport.dpr,0,0,viewport.dpr,0,0);cx.clearRect(0,0,viewport.w,viewport.h);cx.fillStyle='#b6d9bd';cx.fillRect(0,0,viewport.w,viewport.h);let p=projection();cx.setTransform(viewport.dpr*p.scale,0,0,viewport.dpr*p.scale,viewport.dpr*p.tx,viewport.dpr*p.ty);drawMap();if(hoverTile&&selected){cx.fillStyle='rgba(255,242,140,.32)';cx.fillRect(hoverTile.x*T,hoverTile.y*T,T,T);cx.strokeStyle='#fff1a1';cx.lineWidth=2/p.scale;cx.strokeRect(hoverTile.x*T+1,hoverTile.y*T+1,T-2,T-2)}for(let o of getObjects())drawObject(o);for(let c of getCats())drawCat(c)}
$('#itemFilters').addEventListener('click',e=>{let b=e.target.closest('[data-filter]');if(!b)return;activeFilter=b.dataset.filter;renderFilters();renderTools()});$('#tools').addEventListener('click',e=>{let b=e.target.closest('[data-tool]');if(!b)return;selected=selected===b.dataset.tool?null:b.dataset.tool;eraseMode=false;$('#eraseMode').classList.remove('active');$('#eraseMode').setAttribute('aria-pressed','false');renderTools();$('#canvasTip').textContent=selected?`已选${defs.find(d=>d.id===selected).name}：点击空地摆放，拖动画面可移动视角`:'空手时点击猫咪摸摸；拖动地图可移动视角';beep(480)});
function place(x,y){if(x<0||y<0||x>=COLS||y>=ROWS)return;let map=getMap();if(state.mapId==='yard'&&y<2)return msg('wall','这里不方便摆放，请选院子空地');if(map.objects.some(o=>o.x===x&&o.y===y))return msg('occupied','这个位置已有物品，可右键收起');if(map.cats.some(c=>Math.floor(c.x/T)===x&&Math.floor(c.y/T)===y))return msg('cat-tile','猫咪正在这里，换个空地摆放吧');let d=defs.find(a=>a.id===selected);if(!d)return;if(state.coins<d.cost)return msg('funds','金币不足，完成任务可以获得奖励');state.coins-=d.cost;map.objects.push({id:`o-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,type:d.id,x,y});state.placed++;selected=null;renderTools();ui();save();beep(680);setVisitText(`${d.name}放好了，猫咪会自己过来看看。`);msg('place-success','道具摆放成功。')}
function closestCat(x,y){return getCats().slice().sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0]||null}
function removeAt(x,y){let list=getObjects(),i=list.findIndex(o=>o.x===x&&o.y===y);if(i<0){msg('empty-remove','这里没有可收起的物品。');return}let o=list.splice(i,1)[0],d=defs.find(a=>a.id===o.type);state.coins+=Math.floor(d.cost/2);ui();save();msg('remove','物品已收起，退回一半金币。')}
$('#eraseMode').onclick=()=>{eraseMode=!eraseMode;selected=null;renderTools();$('#eraseMode').classList.toggle('active',eraseMode);$('#eraseMode').setAttribute('aria-pressed',String(eraseMode));$('#canvasTip').textContent=eraseMode?'点击要收起的物品':'选道具摆放；拖动地图移动视角';};function handleTap(clientX,clientY){let p=pointWorld(clientX,clientY),x=Math.floor(p.x/T),y=Math.floor(p.y/T);if(x<0||y<0||x>=COLS||y>=ROWS)return;if(eraseMode){removeAt(x,y);return}let cat=getCats().find(c=>Math.abs(c.x-p.x)<21&&Math.abs(c.y-p.y)<24);if(cat&&!selected){cat.mood=Math.min(100,cat.mood+7);cat.bubbleUntil=Date.now()+1300;cat.target=null;setVisitText(`${cat.name}开心地蹭了蹭你的手。`);ui();save(true);beep(850);msg('pet','摸摸头成功！');return}if(selected){place(x,y);return}let o=getObjects().find(a=>a.x===x&&a.y===y);if(o){act(o,closestCat(p.x,p.y),true);return}}
function zoomAt(clientX,clientY,factor){let before=pointWorld(clientX,clientY),r=cv.getBoundingClientRect(),c=camera();c.zoom=Math.max(.72,Math.min(3,c.zoom*factor));let p=projection();c.x=before.x-(clientX-r.left-p.ox)/p.scale;c.y=before.y-(clientY-r.top-p.oy)/p.scale;c.initialized=true;clampCamera();$('#zoomLabel').textContent=Math.round(c.zoom*100)+'%'}
cv.addEventListener('pointerdown',e=>{e.preventDefault();cv.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1)gesture={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};if(pointers.size===2){let a=[...pointers.values()],mx=(a[0].x+a[1].x)/2,my=(a[0].y+a[1].y)/2;pinch={dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),zoom:camera().zoom,anchor:pointWorld(mx,my)};if(gesture)gesture.moved=true}}, {passive:false});
cv.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)){if(e.pointerType==='mouse'){let p=pointWorld(e.clientX,e.clientY);hoverTile={x:Math.floor(p.x/T),y:Math.floor(p.y/T)}}return}pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>=2&&pinch){let a=[...pointers.values()],mx=(a[0].x+a[1].x)/2,my=(a[0].y+a[1].y)/2,dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),r=cv.getBoundingClientRect(),c=camera();c.zoom=Math.max(.72,Math.min(3,pinch.zoom*dist/pinch.dist));let p=projection();c.x=pinch.anchor.x-(mx-r.left-p.ox)/p.scale;c.y=pinch.anchor.y-(my-r.top-p.oy)/p.scale;clampCamera();$('#zoomLabel').textContent=Math.round(c.zoom*100)+'%';return}if(gesture&&gesture.id===e.pointerId){let dx=e.clientX-gesture.lastX,dy=e.clientY-gesture.lastY;if(Math.hypot(e.clientX-gesture.x,e.clientY-gesture.y)>5)gesture.moved=true;if(gesture.moved){camera().x-=dx/projection().scale;camera().y-=dy/projection().scale;camera().initialized=true;clampCamera()}gesture.lastX=e.clientX;gesture.lastY=e.clientY;let p=pointWorld(e.clientX,e.clientY);hoverTile={x:Math.floor(p.x/T),y:Math.floor(p.y/T)}}});
cv.addEventListener('pointerup',e=>{let wasPinch=!!pinch;if(pointers.has(e.pointerId))pointers.delete(e.pointerId);if(wasPinch){pinch=null;gesture=null;save();return}if(gesture&&gesture.id===e.pointerId&&!gesture.moved)handleTap(e.clientX,e.clientY);gesture=null;save()});cv.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);gesture=null;pinch=null});cv.addEventListener('pointerleave',()=>{if(!pointers.size)hoverTile=null});cv.addEventListener('contextmenu',e=>{e.preventDefault();let p=pointWorld(e.clientX,e.clientY);removeAt(Math.floor(p.x/T),Math.floor(p.y/T))});cv.addEventListener('wheel',e=>{e.preventDefault();zoomAt(e.clientX,e.clientY,e.deltaY<0?1.12:.89);save()},{passive:false});
$('#mapSelect').addEventListener('change',e=>{state.mapId=e.target.value;if(!getCats().length)getCats().push(makeCat(state.visits%breeds.length,WW*.5,WH*.45));selected=null;renderTools();ui({roster:true});camera().zoom=Math.max(.8,camera().zoom);clampCamera();save();setVisitText(`来到${mapsDef.find(m=>m.id===state.mapId).name}，猫咪们正在探索。`)});function centerZoom(factor){let r=cv.getBoundingClientRect();zoomAt(r.left+r.width/2,r.top+r.height/2,factor);save()}$('#zoomIn').onclick=()=>centerZoom(1.2);$('#zoomOut').onclick=()=>centerZoom(.83);$('#zoomReset').onclick=()=>{camera().x=0;camera().y=0;camera().zoom=1.15;clampCamera();$('#zoomLabel').textContent='115%';save()};
$('#claim').onclick=()=>{if(state.placed<2||state.claimed)return;state.claimed=true;state.coins+=10;ui();save();msg('original-task','原有任务完成，获得 10 金币。');beep(900)};$('#dailyQuests').addEventListener('click',e=>{let b=e.target.closest('[data-quest]');if(!b)return;let q=dailyDefs.find(x=>x.id===b.dataset.quest),d=state.daily;if(!q||d.claimed[q.id]||(d[q.id]||0)<q.goal)return;d.claimed[q.id]=true;state.coins+=q.reward;renderQuests();ui();save();msg(`quest-${q.id}-${d.date}`,`委托完成，获得 ${q.reward} 金币。`);beep(900)});
function beginRename(id){renaming=id;renderVisitors()}function commitRename(id,value){let c=getCats().find(a=>a.id===id);if(!c){renaming=null;renderVisitors();return}let name=Array.from(String(value).trim()).slice(0,12).join('');if(!name){renaming=null;renderVisitors();return}c.name=name;renaming=null;renderVisitors();save(true);msg('rename','猫咪昵称已保存。')}
$('#visitors').addEventListener('dblclick',e=>{let b=e.target.closest('[data-cat-name]');if(b)beginRename(b.closest('[data-cat]').dataset.cat)});$('#visitors').addEventListener('click',e=>{let b=e.target.closest('[data-edit-cat]');if(b)beginRename(b.dataset.editCat)});
function updateOnlineUI(status,text){$('#onlineStatus').textContent=status;$('#onlineStatus').classList.toggle('connected',status==='已连接');if(text)$('#onlineHint').textContent=text;$('#onlineOpen').hidden=status==='已连接';$('#leaveRoom').hidden=status!=='已连接'}$('#onlineOpen').onclick=()=>$('#onlineModal').classList.add('show');$('#onlineClose').onclick=()=>$('#onlineModal').classList.remove('show');$('#leaveRoom').onclick=()=>window.catOnline?.disconnect?.();$('#onlineModal').addEventListener('click',e=>{if(e.target.id==='onlineModal')e.currentTarget.classList.remove('show')});
$('#sound').onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'♫':'♪';msg(soundOn?'sound-on':'sound-off',soundOn?'音效已开启。':'音效已关闭。');beep(620)};function advanceDay(){let today=dayKey();if(state.daily.date===today)return;state.day++;state.daily={date:today,feed:0,play:0,visitors:0,claimed:{}};ui({quests:true});save();msg('new-day-'+today,'新的一天开始啦，每日委托已更新。')}
function act(o,c,manual=false){if(!c)return;let d=defs.find(x=>x.id===o.type);if(!d)return;c.hunger=Math.max(0,c.hunger-(d.hunger||0));c.mood=Math.min(100,c.mood+(d.mood||0));c.bubbleUntil=Date.now()+1300;c.target=null;c.actionWait=0;if(d.cat==='food')state.daily.feed++;if(d.cat==='play'||d.manual)state.daily.play++;if(d.consumable){let a=getObjects(),i=a.findIndex(x=>x.id===o.id);if(i>=0)a.splice(i,1)}setVisitText(`${c.name}正在${d.cat==='food'?'享用':d.cat==='play'?'玩':'使用'}${d.name}。`);ui({quests:true});save(manual);if(manual){msg(`use-${d.id}`,`${c.name}体验了${d.name}。`);beep(760)}}
function chooseTarget(c){let pool=getObjects().filter(o=>defs.find(d=>d.id===o.type)?.auto);if(!pool.length)return null;let preferred=pool.filter(o=>c.hunger>32?defs.find(d=>d.id===o.type)?.cat==='food':c.mood<82?['play','rest'].includes(defs.find(d=>d.id===o.type)?.cat):defs.find(d=>d.id===o.type)?.cat!=='play');if(!preferred.length)preferred=pool;preferred.sort((a,b)=>Math.hypot((a.x+.5)*T-c.x,(a.y+.5)*T-c.y)-Math.hypot((b.x+.5)*T-c.x,(b.y+.5)*T-c.y));return preferred[0]}
let elapsed=0,uiElapsed=0;function update(dt){elapsed+=dt;uiElapsed+=dt;advanceDay();let simulate=!(window.catOnline?.connected&&!window.catOnline.isHost);if(simulate){for(let c of getCats()){c.hunger=Math.min(100,c.hunger+dt*.2);if(c.hunger>82)c.mood=Math.max(15,c.mood-dt*.12);if(!c.target||!getObjects().some(o=>o.id===c.target)){let o=chooseTarget(c);c.target=o?o.id:null;c.actionWait=0}let o=getObjects().find(x=>x.id===c.target);if(o){let tx=(o.x+.5)*T,ty=(o.y+.5)*T,dx=tx-c.x,dy=ty-c.y,d=Math.hypot(dx,dy);if(d>7){let step=Math.min(d,dt*38);c.x+=dx/d*step;c.y+=dy/d*step;c.face=dx>=0?1:-1}else{c.actionWait=(c.actionWait||0)+dt;if(c.actionWait>5)act(o,c,false)}}}}if(uiElapsed>1){uiElapsed=0;ui()}if(Math.floor(elapsed/8)!==Math.floor((elapsed-dt)/8))save()}
setInterval(()=>{if(window.catOnline?.connected&&!window.catOnline.isHost)return;let m=getMap();if(!m.objects.length||m.cats.length>=4)return;let kind=state.visits%breeds.length,c=makeCat(kind,Math.max(2*T,camera().x+T),Math.min(WH-2*T,camera().y+WH*.48));m.cats.push(c);state.visits++;state.daily.visitors++;ui({roster:true,quests:true});save();setVisitText(`${c.name}（${breeds[kind].breed}）闻着食物香味来串门啦！`);beep(560)},30000);
function applySharedSnapshot(snap){if(!snap||!snap.maps)return;let oldMap=state.mapId,oldCount=state.maps[snap.mapId]?.cats?.length||0;applyingRemote=true;state.mapId=mapsDef.some(m=>m.id===snap.mapId)?snap.mapId:state.mapId;for(let d of mapsDef){let src=snap.maps[d.id];if(!src)continue;state.maps[d.id].objects=Array.isArray(src.objects)?src.objects:[];state.maps[d.id].cats=Array.isArray(src.cats)?src.cats.map(fixCat):[];if(src.camera)state.maps[d.id].camera={...state.maps[d.id].camera,...src.camera}}let newCount=state.maps[state.mapId].cats.length;if(oldMap===state.mapId&&newCount>oldCount)state.daily.visitors+=newCount-oldCount;ui({roster:true,quests:true});try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}applyingRemote=false}
window.catGame={getSharedSnapshot:sharedSnapshot,applySharedSnapshot,setOnlineUI:updateOnlineUI,setOnlineMessage:s=>$('#onlineMessage').textContent=s,afterConnected:()=>$('#onlineModal').classList.remove('show')};
renderFilters();renderTools();ui({roster:true,quests:true});resizeCanvas();$('#zoomLabel').textContent=Math.round(camera().zoom*100)+'%';paint();let lastFrame=performance.now();function frame(now){let dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;update(dt);paint();requestAnimationFrame(frame)}requestAnimationFrame(frame);














