import firebaseConfig from './firebase-config.js';
const $=s=>document.querySelector(s),ready=['apiKey','authDomain','databaseURL','projectId','appId'].every(k=>typeof firebaseConfig?.[k]==='string'&&firebaseConfig[k].length>0);let auth=null,db=null,uid=null,room=null,isHost=false,unsub=[],pending=null,pushTimer=null,meta=null;
function say(s){$('#onlineMessage').textContent=s}function status(label,text){window.catGame?.setOnlineUI(label,text);$('#leaveRoom').hidden=label!=='已连接';$('#onlineOpen').hidden=label==='已连接'}function setRoomCode(code){$('#roomCode').value=code;$('#onlineHint').textContent=`房间码 ${code} · 邀请好友加入`;$('#onlineMessage').textContent=`房间码：${code}。把这个码发给好友即可一起玩。`}
if(!ready){status('待配置','联机暂未配置，单机地图和任务可正常游玩。');for(const id of ['createRoom','joinRoom'])$('#'+id).addEventListener('click',()=>say('要启用好友联机，请先配置 Firebase 网页应用、匿名登录和 Realtime Database 安全规则。'))}
else try{const v='12.19.0',base=`https://www.gstatic.com/firebasejs/${v}`;const [appSdk,authSdk,dbSdk]=await Promise.all([import(`${base}/firebase-app.js`),import(`${base}/firebase-auth.js`),import(`${base}/firebase-database.js`)]);const app=appSdk.initializeApp(firebaseConfig);auth=authSdk.getAuth(app);db=dbSdk.getDatabase(app);const{signInAnonymously}=authSdk,{ref,get,set,update,remove,onValue,onDisconnect,runTransaction}=dbSdk;
async function user(){if(!auth.currentUser)await signInAnonymously(auth);uid=auth.currentUser.uid;return uid}function code(){let a=new Uint32Array(8);crypto.getRandomValues(a);let chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from(a,n=>chars[n%chars.length]).join('')}
function listen(codeValue,host){room=codeValue;isHost=host;let root=`rooms/${room}`,sharedRef=ref(db,`${root}/shared`),playersRef=ref(db,`${root}/players`),metaRef=ref(db,`${root}/meta`);unsub.forEach(f=>f());unsub=[];onDisconnect(ref(db,`${root}/players/${uid}`)).remove();unsub.push(onValue(sharedRef,s=>{if(s.exists())window.catGame?.applySharedSnapshot(s.val())}));unsub.push(onValue(playersRef,s=>{let list=s.val()||{},count=Object.keys(list).length;$('#onlineHint').textContent=`房间码 ${room} · ${count}/2 位玩家在线`;if(count<2&&isHost)$('#onlineMessage').textContent=`房间码：${room}。等待好友加入…`;if(!list[uid]){disconnect(false);return}if(!list[meta?.host]&&count===1)isHost=true;status('已连接',`房间码 ${room} · ${count}/2 位玩家在线`)}));unsub.push(onValue(metaRef,s=>{meta=s.val();if(meta?.closed){say('房主已结束房间。');disconnect(false)}}));setRoomCode(room);status('已连接',`房间码 ${room} · 1/2 位玩家在线`);window.catOnline={connected:true,get isHost(){return isHost},stateChanged,createRoom,joinRoom,disconnect};window.catGame?.afterConnected()}
async function createRoom(name=''){say('正在创建好友房间…');status('连接中','正在连接实时房间…');try{await user();let codeValue,ok=false;for(let i=0;i<8&&!ok;i++){let candidate=code(),result=await runTransaction(ref(db,`rooms/${candidate}/meta`),current=>current===null?{host:uid,createdAt:Date.now(),closed:false}:undefined,{applyLocally:false});if(result.committed){codeValue=candidate;ok=true}}if(!ok)throw Error('暂时无法分配房间码，请重试。');let root=`rooms/${codeValue}`;meta={host:uid};await set(ref(db,`${root}/players/${uid}`),{name:String(name||'小院访客').slice(0,12),joinedAt:Date.now()});await set(ref(db,`${root}/shared`),window.catGame.getSharedSnapshot());listen(codeValue,true)}catch(e){status('未连接','联机连接失败。');say(e.message||'创建房间失败，请检查 Firebase 配置和安全规则。')}}
async function joinRoom(codeValue,name=''){codeValue=String(codeValue||'').trim().toUpperCase();if(!/^[A-HJ-NP-Z2-9]{8}$/.test(codeValue)){say('房间码是 8 位大写字母或数字。');return}say('正在加入好友房间…');status('连接中','正在连接实时房间…');try{await user();let root=`rooms/${codeValue}`,mr=ref(db,`${root}/meta`),m=(await get(mr)).val();if(!m||m.closed)throw Error('房间不存在或已关闭，请确认房间码。');let pr=ref(db,`${root}/players`),players=(await get(pr)).val()||{};if(!players[uid]&&Object.keys(players).length>=2)throw Error('房间已满，目前最多支持 2 位玩家。');await set(ref(db,`${root}/players/${uid}`),{name:String(name||'小院访客').slice(0,12),joinedAt:Date.now()});meta=m;let shared=(await get(ref(db,`${root}/shared`))).val();if(shared)window.catGame.applySharedSnapshot(shared);listen(codeValue,m.host===uid)}catch(e){status('未连接','联机连接失败。');say(e.message||'加入失败，请检查房间码和安全规则。')}}
function stateChanged(snapshot,forceCats=false){if(!room)return;pending={snapshot,forceCats};clearTimeout(pushTimer);pushTimer=setTimeout(async()=>{if(!room||!pending)return;let p=pending;pending=null;try{await runTransaction(ref(db,`rooms/${room}/shared`),current=>{if(!current)return p.snapshot;let merged={mapId:p.snapshot.mapId,maps:{}};for(let id of ['yard','forest','coast']){let next=p.snapshot.maps[id],old=current.maps?.[id]||{};merged.maps[id]={objects:next.objects,cats:isHost||p.forceCats?next.cats:(old.cats||next.cats),camera:next.camera}}return merged},{applyLocally:false})}catch(e){say('同步暂时中断，检查网络后再试。')}},250)}
async function disconnect(closeRoom=true){let old=room;if(!old)return;let wasHost=isHost,root=`rooms/${old}`;clearTimeout(pushTimer);unsub.forEach(f=>f());unsub=[];try{if(closeRoom&&wasHost)await update(ref(db,`${root}/meta`),{closed:true});await remove(ref(db,`${root}/players/${uid}`));if(closeRoom&&wasHost)await remove(ref(db,`${root}/shared`))}catch{}room=null;meta=null;isHost=false;window.catOnline={connected:false,isHost:false,stateChanged(){},createRoom,joinRoom,disconnect};status('单机','已退出好友房间。');say('你已回到自己的小院。')}
$('#createRoom').addEventListener('click',()=>createRoom($('#playerName').value));$('#joinRoom').addEventListener('click',()=>joinRoom($('#roomCode').value,$('#playerName').value));$('#leaveRoom').addEventListener('click',()=>disconnect(true));status('单机','好友联机已就绪，创建房间或输入好友的房间码。');window.catOnline={connected:false,isHost:false,stateChanged(){},createRoom,joinRoom,disconnect};
}catch(e){status('未连接','联机模块载入失败，单机不受影响。');say('Firebase SDK 无法加载，请刷新页面或检查网络。');console.error('Cat yard online setup failed',e)}

