const $=s=>document.querySelector(s);
const PEER_OPTIONS={host:'0.peerjs.com',port:443,secure:true,path:'/'};
const CODE_CHARS='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const roomPattern=/^[A-HJ-NP-Z2-9]{8}$/;
let PeerCtor=null,peer=null,connection=null,room='',isHost=false,playerName='',loading=false;
function say(text){$('#onlineMessage').textContent=text}
function setStatus(label,text){window.catGame?.setOnlineUI(label,text);if($('#leaveRoom'))$('#leaveRoom').hidden=label!=='已连接';if($('#onlineOpen'))$('#onlineOpen').hidden=label==='已连接'}
function setRoomCode(code){room=code;$('#roomCode').value=code;$('#onlineHint').textContent=`房间码 ${code} · 把房间码发给好友`;say(`房间码：${code}。好友输入这个码即可加入。`);if($('#copyRoom'))$('#copyRoom').hidden=false;try{history.replaceState(null,'',`${location.pathname}${location.search}#room=${code}`)}catch{}}
function publishApi(){window.catOnline={connected:!!peer&&!peer.destroyed,isHost,stateChanged,createRoom,joinRoom,disconnect}}
function snapshot(){return window.catGame?.getSharedSnapshot?.()||null}
function send(message){if(connection?.open)try{connection.send(message);return true}catch{}return false}
function refreshStatus(){let count=connection?.open?2:1;setStatus('已连接',`房间码 ${room} · ${count}/2 位玩家在线`);$('#onlineHint').textContent=`房间码 ${room} · ${count}/2 位玩家在线`}
function randomCode(){let out='';for(let i=0;i<8;i++)out+=CODE_CHARS[Math.floor(Math.random()*CODE_CHARS.length)];return out}
function openPeer(id){return new Promise((resolve,reject)=>{let p;try{p=new PeerCtor(id||undefined,PEER_OPTIONS)}catch(e){reject(e);return}let done=false;const fail=e=>{if(done)return;done=true;try{p.destroy()}catch{}reject(e)};p.once('open',()=>{if(done)return;done=true;resolve(p)});p.once('error',fail);p.on('disconnected',()=>{if(p===peer&&!p.destroyed){setStatus('未连接','联机信号暂时断开，请重新创建或加入房间。');say('网络连接暂时断开。')}})})}
function sendSnapshot(type='snapshot'){let s=snapshot();if(s)send({type,snapshot:s})}
function handleData(message){if(!message||typeof message!=='object')return;if(message.type==='hello'&&isHost){sendSnapshot();return}if(message.type==='snapshot'&&!isHost){if(message.snapshot)window.catGame?.applySharedSnapshot(message.snapshot);refreshStatus();return}if(message.type==='change'&&isHost&&message.snapshot){window.catGame?.applySharedSnapshot(message.snapshot);sendSnapshot()}}
function attachConnection(c,hostSide){if(connection&&connection!==c){try{c.close()}catch{};return}connection=c;isHost=hostSide;c.on('open',()=>{if(hostSide)sendSnapshot();else send({type:'hello',name:playerName});refreshStatus();publishApi()});c.on('data',handleData);c.on('close',()=>{if(connection!==c)return;connection=null;if(isHost){setStatus('已连接',`房间码 ${room} · 1/2 位玩家在线`);$('#onlineHint').textContent=`房间码 ${room} · 等待好友加入`;say('好友已离开房间，仍可继续等待新的加入。')}else{setStatus('未连接','好友已离开房间。');say('好友已离开房间。');disconnect(false)}publishApi()});c.on('error',()=>{if(connection===c)say('房间连接出现波动，请检查网络。')})}
function stateChanged(s){if(!s||!connection?.open)return;send({type:isHost?'snapshot':'change',snapshot:s})}
async function createRoom(name=''){if(loading)return;loading=true;playerName=String(name||'小院访客').trim().slice(0,12)||'小院访客';say('正在创建好友房间…');setStatus('连接中','正在连接房间服务…');try{await disconnect(false);if(!PeerCtor)throw Error('联机组件还没有加载完成，请刷新页面再试。');let p=null,code='';for(let i=0;i<5&&!p;i++){try{code=randomCode();p=await openPeer(code)}catch(e){if(e?.type!=='unavailable-id')throw e}}if(!p)throw Error('房间码暂时不可用，请重新创建。');peer=p;room=code;isHost=true;setRoomCode(code);p.on('connection',c=>attachConnection(c,true));setStatus('已连接',`房间码 ${room} · 1/2 位玩家在线`);publishApi()}catch(e){setStatus('未连接','联机连接失败。');say(e.message||'创建房间失败，请检查网络后重试。')}finally{loading=false}}
async function joinRoom(rawCode,name=''){if(loading)return;let code=String(rawCode||'').trim().toUpperCase();if(!roomPattern.test(code)){say('房间码需要是 8 位大写字母或数字。');return}loading=true;playerName=String(name||'小院访客').trim().slice(0,12)||'小院访客';say('正在加入好友房间…');setStatus('连接中','正在连接好友房间…');try{await disconnect(false);if(!PeerCtor)throw Error('联机组件还没有加载完成，请刷新页面再试。');peer=await openPeer();room=code;isHost=false;peer.on('connection',c=>attachConnection(c,false));let c=peer.connect(room,{reliable:true,serialization:'json'});attachConnection(c,false);await new Promise((resolve,reject)=>{let timer=setTimeout(()=>reject(Error('连接超时，请确认房间码正确且房主在线。')),12000);c.once('open',()=>{clearTimeout(timer);resolve()});c.once('error',e=>{clearTimeout(timer);reject(e)})});setRoomCode(code);setStatus('已连接',`房间码 ${room} · 2/2 位玩家在线`);publishApi()}catch(e){setStatus('未连接','联机连接失败。');say(e.message||'加入失败，请确认房间码和网络。');try{peer?.destroy()}catch{}peer=null;connection=null;publishApi()}finally{loading=false}}
async function disconnect(){let p=peer;peer=null;connection=null;isHost=false;room='';try{p?.destroy()}catch{}if($('#copyRoom'))$('#copyRoom').hidden=true;try{history.replaceState(null,'',location.pathname+location.search)}catch{}publishApi();setStatus('单机','已退出好友房间。');say('你已回到自己的小院。')}
async function copyRoom(){if(!room)return;try{await navigator.clipboard.writeText(room);say('房间码已复制，可以发给好友了。')}catch{say(`请手动复制房间码：${room}`)}}
$('#createRoom').addEventListener('click',()=>createRoom($('#playerName').value));$('#joinRoom').addEventListener('click',()=>joinRoom($('#roomCode').value,$('#playerName').value));$('#leaveRoom').addEventListener('click',()=>disconnect());$('#copyRoom')?.addEventListener('click',copyRoom);$('#onlineModal').addEventListener('click',e=>{if(e.target.id==='onlineModal')e.currentTarget.classList.remove('show')});
function loadPeer(src){return new Promise((resolve,reject)=>{let script=document.createElement('script');script.src=src;script.onload=()=>window.Peer?resolve(window.Peer):reject(Error('PeerJS unavailable'));script.onerror=()=>reject(Error('PeerJS CDN unavailable'));document.head.appendChild(script)})}
setStatus('连接中','正在加载好友联机组件…');publishApi();
(async()=>{try{let errors=[];for(let src of ['https://cdn.jsdelivr.net/npm/peerjs@1.5.4/dist/peerjs.min.js','https://unpkg.com/peerjs@1.5.4/dist/peerjs.min.js']){try{PeerCtor=await loadPeer(src);break}catch(e){errors.push(e)}}if(!PeerCtor)throw errors[0]||Error('PeerJS unavailable');let hash=location.hash.match(/^#room=([A-HJ-NP-Z2-9]{8})$/i)?.[1];if(hash)$('#roomCode').value=hash.toUpperCase();setStatus('单机','好友联机已就绪，创建房间或输入好友房间码。')}catch(e){setStatus('未连接','联机组件加载失败，单机功能仍可使用。');say('好友联机组件加载失败，请刷新页面或检查网络。');console.error('Cat yard peer setup failed',e)}})();
